name: Nightly Test run

on:
  workflow_dispatch:

jobs:
  integration-tests-rl:
    name: Integration Tests (Jahia-RL)
    secrets: inherit
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    with:
      module_id: database-connector
      jahia_image: jahia/jahia-ee:8
      provisioning_manifest: provisioning-manifest-build.yml
      artifact_prefix: dbconn-jahia-rl
      timeout_job: 45
      timeout_step: 20
